### ISSUE TITLE
Generally slow performance on BareMetal, KVM and Docker

### ISSUE THREAD

**Issue by venomone** [storj/gateway-st#35]
Hey folks, I already opened several support ticket with the StorJ support team but sadly I'm not able to fix my performance issues...
I have had the minio Gateway implementation running under docker, K8s (docker), directly on my Workstation and on several different cloud providers and I'm not able to get more than 10-20 MB/s per IP/connection. For example if I download one file I get 15 MB/s if I download two files I get 7.5 MB/s per connection, why that?
I need massive throughput of 50 MB/s per connection at least!
All our servers are connected with at least 10 Gbit/s to the public so I would expect that this is not the bottleneck. I also dont see my CPU resources going up so the only thing that I can assume that the StorJ Network is simply slow?!?

StorJ minio Gateway: 
2%[>                                                                 ] 250.00M  7.00MB/s    eta 29m 48s

Test Download from Hetzner:
81%[====================================================>             ] 814.13M   110MB/s    eta 2s

I really don't get the deal here. Either StorJ is able to provide a Stable Bandwidth or not but than I dont need this products at all as I cannot send out files to my clients at mass ...

Please help and provide a solution instead of pointing onto my servers. Are there maybe sysctl parameters that needs to be set properly I'm not aware of?

**Comment by amwolff** [comment]
Hi @venomone,

With the default sysctls for, e.g. Debian or Ubuntu, you should be able to download from Gateway-ST with 50MB/s, so before with start tuning the kernel parameters, i.e. sysctls, I believe we should try simpler things first.

---

I have a couple of suggestions you can try.

1) Check orchestration limits

It sounds as if Gateway-ST is hitting some wall with 15MB/s for all connections. Have you tried running it bare-metal-like to see if there's any difference? I guess that would be the easiest to find out if we are limited by Docker/k8s here. If we are, we could dig deeper in this direction.

2) Check MinIO's throttling

With Gateway-ST, Storj's gateway runs as a fully-featured MinIO's gateway (storage backend), so you can also be blocked by connection limits and connections deadlines. More: https://github.com/minio/minio/tree/master/docs/throttle

**Comment by venomone** [comment]
@amwolff

I tried running the gateway on a Virtual Machine (KVM) with 10 Gbit/s Up/Down-link and I've also tried running the gateway on my local bare-metal machine with 500 Mbit/s downlink / 50 Mbit/s uplink.


Here are my findings:

On metal it seems to run much better but the question is why?

To me, it somehow looks like that the gateway needs a lot of CPU resources while putting the files-snippets within the StorJ network back together while downloading a object using the gateway.

Does StorJ Encryption/Decryption rely onto some specific CPU extension that speed things up?
I'm asking because the CPU load using docker is 75% if I download a file while on the metal machine it's almost not noticeable ...

Anyways, I'm not able to bypass the magic mark of 20 Mb/s per download connection on any of my setups.
The only way I get more that 20 MB/s is if I open multiple connections to download the file and only if I dont use docker.
I tried it with docker, without docker, on metal, on massive capacity networks ... No matter what I tried I don't get the gateway to perform like it should in my opinion. So either StorJ is simply slow by nature due to multiple factors or I'm doing something very wrong and don't know where to look at.

Can you please test for yourself if you get more than 20 MB/s out of this.
Would be awesome to see another comparison on meta vs. docker according to the gateway software.


Thanks in advance.

**Comment by dominickmarino** [comment]
Given the number of variables in play, we would like to offer you a working session to help tune your installation. I'll reach out by email to schedule momentarily.

**Comment by venomone** [comment]
Are you talking about the general support desk?
Thanks by the way ;)

**Comment by dominickmarino** [comment]
> Are you talking about the general support desk? Thanks by the way ;)

I reached out via email earlier today. I'm a Solutions Architect and I assist the support team in instances like this. Please respond when you have a moment and we will schedule your support session. Excited to assist.

**Comment by venomone** [comment]
Okay, let's see, maybe tomorrow fits. One thing in forehand, can you image that the CPU load comes from a long encryption key? as the phrase I use for encryption is very long, more than 100 characters ...

**Comment by dominickmarino** [comment]
Again would be great to meet today to fully understand your use case. We commonly see multi Gb/s transfer speeds and I'm confident we can get you transferring much faster. 

From your screenshot it appears you are using GWST and S3 browser. Can you tell us in detail about how your clients retrieve your files? If looking for a GUI alternative you could just run FileZilla which has embedded uplink, one and done. If wanting the best speed let's move away from GUI tools and use Rclone. Please see the following excerpt from our performance tuning documentation. The Key is, you can offload the compute burden to us if you wish. 
________
For downloading many files that do not benefit from large parallelism due to being smaller in size (<64MB) the best way to get the greatest overall throughput is to download many files at one time, RCLONE is great for this. This can be done via either the hosted Gateway MT or native methods. If you implement a native method you bypass our edge services which is the slightly more performant path. The commands below are agnostic to the method for which you implement RCLONE. 

Depending on the integration method you will either have high or low CPU utilization. 

**Native**
This will be the fastest with adequate compute. Increase --transfers until you have reached your throughput goal or limit of acceptable compute. 

**Hosted Gateway MT**
If you have lower compute capability this may be faster. It is worth testing both integration patterns and seeing what works best for you. Increase --transfers until you have reached your throughput goal.

**Example Commands** 
The following command will download 10 files at the same time. I tend to advise 2x transfers per CPU core if using the native integration and much higher figures off using the hosted gateway that offloads the computer burden to our edge services. 
```rclone copy --progress --transfers 10 remote:bucket /tmp```

**Comment by venomone** [comment]
Hello again, well that was a bunch of very useful information.
Basically we use the Gateway for only to serve static downloads.
Anyway, a good practice to test download speed is also "aria", simply do:

`aria2c -x 16 (for 16 download threads)`

no need to fuzz around with rclone, cheers

**Comment by amwolff** [comment]
Hi, @venomone.

> To me, it somehow looks like that the gateway needs a lot of CPU resources while putting the files-snippets within the StorJ network back together while downloading a object using the gateway.

This is true that downloading an object from the Storj network will require more CPU time than a "normal" download, but it shouldn't overload the system as long as you are not downloading hundreds of objects in parallel on average hardware.

> Does StorJ Encryption/Decryption rely onto some specific CPU extension that speed things up? I'm asking because the CPU load using the VM together with docker is 75% if I download a file while on the metal machine it's almost not noticeable ...

Encryption/decryption almost always relies on supplementary instructions. Additionally, we use [infectious](https://github.com/vivint/infectious) for Reed-Salomon forward error correction with Berlekamp-Welch decoder to reconstruct uploaded objects from downloaded pieces. As far as I'm aware, this library uses vector extensions especially, so if VM's virtual CPU wouldn't have modern supplementary instructions available, I can imagine this will take its toll on system load.

It would be best to take a CPU profile when this happens to you to avoid further guessing. If this is something you could do to help us diagnose the issue, that would be amazing.

To take a CPU profile of Gateway-ST under load:

1. Make sure you have Go installed:

https://go.dev/dl/

2. After you start Gateway-ST, it will log the current debug port:

`2022-01-10T15:29:00.270+0100	DEBUG	process/debug.go:37	debug server listening on 127.0.0.1:49189`

3. Execute while doing what causes Gateway-ST to hammer CPU:

`go tool pprof http://127.0.0.1:49189/debug/pprof/profile`

4. After the profile has been taken, generate the report:

```
Fetching profile over HTTP from http://127.0.0.1:49189/debug/pprof/profile
Saved profile in /Users/artur/pprof/pprof.samples.cpu.002.pb.gz
Type: cpu
Time: Jan 10, 2022 at 3:30pm (CET)
Duration: 30s, Total samples = 180ms (  0.6%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) png
Generating report in profile001.png
```

This way, we will see where Gateway-ST spends the most time and whether this is expected.

Here's how the report will look like (but your report might be drastically different):

![profile001](https://user-images.githubusercontent.com/30234756/148783086-c95c34fb-7e95-48dc-9c63-d78ad7b5c670.png)

Apart from great suggestions by Dominick, here's my general advice:

- If you use multipart upload to upload objects, ensure the configured part size is 64MiB or multiples. Otherwise, while downloading big objects, performance could plummet;
- If you use AWS CLI or AWS SDK for your language of choice, make sure you exploit parallelism to download objects (specifically for big objects). 20MB/s is something I have even seen with AWS S3 without parallelism enabled.

**Comment by venomone** [comment]
@amwolff Thanks for pointing out all these very useful information. I will try to create a report accordingly as soon as I'm back at the office. In the meantime I also tried a very "Up-to-date/New" CPU and the result is now also much better. I first was working with a E5-2630v2, this Chip is from ~2014, maybe this was the actual issue here.
Now running on 4 Cores under KVM with a 2690v4 Chip and things are now much smother.
Anyway, I will try to post the repo here, just to make things clear.


Thank again :)

**Comment by venomone** [comment]
The question is solved from my position. I now have multiple systems' setup that work as gateway with a load-balancer in front, works like a charm but I'm missing the full s3 compatibility. Hopefully we will see more in the future here.

**Comment by venomone** [comment]
Solved
