### ISSUE TITLE
Invalid UI version in the JSON-RPC response

### ISSUE THREAD

**Issue by venomone** [storj/gateway-st#59]
Hey folks,

I just updated my gateway binary, and it seems something is messed up, if I try to login to minio using the build-in UI I just get "Invalid UI version in the JSON-RPC response"

In addition, I also found this: https://github.com/minio/minio/issues/12450 which describes my problem very well, but the solution does not work for me here as the storj minio client is a fork and I have no idea about the code state. Any help would be nice.
![minio](https://user-images.githubusercontent.com/43114687/155745797-42c8562b-586c-49f1-8677-fc626aec26e8.png)

**Comment by amwolff** [comment]
Hi @venomone! We are aware of the issue (#52), and it's already fixed on the `main` branch. We missed the release on Monday due to the holiday, but I'm trying to schedule it today.

Meanwhile, you can try testing the object browser using the following image: [storjlabs/gateway:85e6166-go1.17.5](https://hub.docker.com/layers/storjlabs/gateway/85e6166-go1.17.5/images/sha256-03204647ce60f4c0345d7d76726bfe2591d3432c2826b67359281a83d7d8d2c7?context=explore). It should work correctly.

Thanks a lot for using Gateway-ST.

**Comment by amwolff** [comment]
[v1.6.1](https://github.com/storj/gateway-st/releases/tag/v1.6.1) is live now.
